Incremental updates for the whole project
Motivation
The project has not been updated for a long time. Its dependencies are out-dated.

Changes:
0. To make our life easier, all modules are disabled temporarily except for jpa.
1. The in-memory database is switched from HSQL to H2.
2. All dependencies are updated to either latest or not-to-old versions. For that matter, plenty of user code is corrected.
3. Removed hibernate-jpa-2.0-api as dependency, allowing hibernate introducing its own version. This fixed NoSuchMethodError in javax.persistence.Table.indexes()[Ljavax/persistence/Index.
4. Enabled auto-wiring.
5. The choices of logging framworks are pinned down to SLF4J+logback.
6. The logback.xml is updated to 1) log start-up context info 2) write to console and file 3) include more sections in patterns.
7. The entity ID generation strategy has been changed to GenerationType.IDENTITY to fix primary key violation for the models.

Results:
1. Now all jpa tests run fine.
2. Other modules shall be fixed and then re-enabled in latter patches.